Use university;

DROP TABLE IF EXISTS Course;

CREATE TABLE Course (
    CourseNo VARCHAR(10) PRIMARY KEY,
    CrsDesc TEXT NOT NULL,
    CrsUnits INT NOT NULL
);


INSERT INTO Course VALUES ('FIN300', 'FUNDAMENTALS OF FINANCE', 4);
INSERT INTO Course VALUES ('FIN450', 'PRINCIPLES OF INVESTMENTS', 4);
INSERT INTO Course VALUES ('FIN480', 'CORPORATE FINANCE', 4);
INSERT INTO Course VALUES ('IS320', 'FUNDAMENTALS OF BUSINESS PROGRAMMING', 4);
INSERT INTO Course VALUES ('IS460', 'SYSTEMS ANALYSIS', 4);
INSERT INTO Course VALUES ('IS470', 'BUSINESS DATA COMMUNICATIONS', 4);
INSERT INTO Course VALUES ('IS480', 'FUNDAMENTALS OF DATABASE MANAGEMENT', 4);

SELECT * FROM Course;